name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      -  17394-gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'  # Checkout submodules
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements-3.11.txt 

      - name: Run Custom Script
        run: ./bin/build.sh copy_recipes  # Executing your custom script

      - name: Build Docs
        run: |
          make html

      - name: Create CNAME
        run: echo 'docs.howso.com' > ./build/html/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
          publish_branch: gh-pages

